### PR TITLE
Wq rebalance

### PR DESCRIPTION
**Pull request by stupidnewbie**
WQ have four ships that just aren't useful.  The Negotiator is currently a weaker trader than the starter ship.  The hunters only have two hard points.  And the Blockade Runner cost is in line with end game traders but without the stats to back it up.  I'm proposing the following in the interest of making the ships useful:

Negotiator - turn in to an early game trader
cost quadrupled to justify stat buffs.  
+50 armor and shields to shore up defense in line with other ships around new cost.
+90 cargo holds.  this brings trading power to 1430.  93% of a Merchant Vessel.
add cloak.  WQ ships should cloak.
a trade ship like this would give WQ players a way to generate a bit of fast cash to hop in to a hunter early on.  the cloak is a way to justify keeping it over a MV while trading towards a larger ship.

Resistance - convert early game hunter
+1 hard point to 3.  can't hunt trade ships when you're out gunned by them.
given the stats and price point this will become an effective hunter very early in the game.

Rogue - convert to small mid game hunter
+50% cost to justify stat increases.
+2 hard points to 4.
-200 armor to keep D in line with hunters of similar cost.
this will turn in to a sort of mini-Assassin.

Blockade Runner - convert to mid game trader
cost cut in half which puts it near the top of mid tier traders.  close to Favored Offspring.
-1 hard point to bring firepower more in line with ships of similar cost and purpose.  but still formidable at 2HP + 50CD.
-100 to shields and armor to bring defense more in line with ships of similar cost.
additional 15 holds bring trade power to 1710.  90% of a thief and 102% of a leviathan.
this will still be expensive but it will also be a strong mid tier trade ship.

### CODE REVIEW

**Comment by hemberger** [comment]
Thanks for the PR! Are you able to provide a .smr file/snippet with the changes reflected? If readily available, this would speed up my ability to review the new ships. This is a big enough change that it would probably need to go through some kind of community review as well. 

Also, at some point before we merge this PR we'll want to add a newline to the end of the patch file.

**Comment by stupidnewbie** [comment]
Here it is in SMR format:

```
Negotiator=WQ Human,620936,11,1,5,Trader,ShipEquipment=Shields=250;Armor=200;Cargo Holds=130;Combat Drones=0;Scout Drones=10;Mines=0;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Resistance=WQ Human,1156265,8,3,9,Hunter,ShipEquipment=Shields=300;Armor=250;Cargo Holds=90;Combat Drones=10;Scout Drones=10;Mines=10;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Rogue=WQ Human,3112290,10,4,9,Hunter,ShipEquipment=Shields=425;Armor=350;Cargo Holds=120;Combat Drones=50;Scout Drones=50;Mines=50;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Blockade Runner=WQ Human,2565536,9,2,13,Trader,ShipEquipment=Shields=450;Armor=400;Cargo Holds=190;Combat Drones=50;Scout Drones=10;Mines=20;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
```

**Comment by witold-cyrek** [comment]
Negotiater will proably become a scout ship. Blockade Runner will get sexy boost to trade potential if trading evil goods.

**Comment by stupidnewbie** [comment]
The negotiator would make a good scout ship also.  That smuggler bonus is trash and will keep the BR being a status symbol for people who are bad at trading.

**Pull request closed without merging**
