### PR TITLE
Starter ship rebalance

### PR DESCRIPTION
**Pull request by stupidnewbie**
These proposed changes will nearly double the trading power of starting ships.  I hope to smooth the learning curve slightly by doing this.  Veterans will rarely pilot these ships but newbies will certainly spend some time in them.

Alskant ships are adjusted to be the strongest trader followed by the combat weaker WQ/Human and Ik'Thorne.  The more combat oriented Salvene/Thevian/Nijarin make up the next pack and Creonti are at the bottom.

The two neutral starting ships are also improved.  This may create situations where it is effective to actually use them.

### CODE REVIEW

**Comment by hemberger** [comment]
Thanks for the pull request!

I think the Galactic Semi should probably stay the same, since it is a special ship (e.g. for Semi Wars). If you can provide a `.smr` file with these changes, that would help speed up the review and be much appreciated! :)

**Comment by stupidnewbie** [comment]
Removed Galactic Semi changes.

SMR text:
```[Ships]
; Name = Race,Cost,TPH,Hardpoints,Power,+Equipment (Optional),+Restrictions(Optional)
; Restrictions:Align(Integer)
A Hatchling's Due=Salvene,0,7,1,5,ShipEquipment=Shields=150;Armor=200;Cargo Holds=100;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Advanced Carrier=Ik'Thorne,5610264,9,2,9,ShipEquipment=Shields=700;Armor=150;Cargo Holds=150;Combat Drones=20;Scout Drones=0;Mines=50;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Advanced Courier Vessel=Neutral,5560740,10,2,9,ShipEquipment=Shields=250;Armor=250;Cargo Holds=235;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Ambassador=Human,1792187,9,1,5,ShipEquipment=Shields=500;Armor=450;Cargo Holds=150;Combat Drones=10;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Armoured Semi=Neutral,122152,7,1,5,ShipEquipment=Shields=225;Armor=350;Cargo Holds=140;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Assassin=Neutral,12483452,11,5,19,ShipEquipment=Shields=500;Armor=400;Cargo Holds=120;Combat Drones=10;Scout Drones=0;Mines=25;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=2
Assault Craft=Thevian,12789862,10,6,22,ShipEquipment=Shields=950;Armor=950;Cargo Holds=30;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Battle Cruiser=Neutral,3628134,7,5,19,ShipEquipment=Shields=525;Armor=500;Cargo Holds=0;Combat Drones=25;Scout Drones=0;Mines=100;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Blockade Runner=WQ Human,5131071,9,3,13,ShipEquipment=Shields=550;Armor=500;Cargo Holds=175;Combat Drones=10;Scout Drones=0;Mines=20;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Border Cruiser=Human,6887432,8,4,16,ShipEquipment=Shields=575;Armor=600;Cargo Holds=120;Combat Drones=50;Scout Drones=0;Mines=150;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Bounty Hunter=Thevian,1768634,11,3,13,ShipEquipment=Shields=550;Armor=650;Cargo Holds=70;Combat Drones=50;Scout Drones=0;Mines=75;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Carapace=Thevian,6045094,11,5,19,ShipEquipment=Shields=600;Armor=700;Cargo Holds=30;Combat Drones=50;Scout Drones=0;Mines=100;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Celestial Combatant=Neutral,2656949,9,4,16,ShipEquipment=Shields=400;Armor=350;Cargo Holds=95;Combat Drones=5;Scout Drones=0;Mines=20;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Celestial Mercenary=Neutral,2865997,9,3,13,ShipEquipment=Shields=300;Armor=275;Cargo Holds=75;Combat Drones=5;Scout Drones=0;Mines=10;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Celestial Trader=Neutral,435969,9,1,5,ShipEquipment=Shields=250;Armor=275;Cargo Holds=80;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Dark Mirage=WQ Human,10088764,9,6,22,ShipEquipment=Shields=825;Armor=825;Cargo Holds=60;Combat Drones=0;Scout Drones=0;Mines=30;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Deal-Maker=Alskant,5727059,11,2,9,ShipEquipment=Shields=250;Armor=200;Cargo Holds=200;Combat Drones=10;Scout Drones=0;Mines=15;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Death Cruiser=Neutral,25890100,9,6,22,ShipEquipment=Shields=800;Armor=400;Cargo Holds=100;Combat Drones=20;Scout Drones=0;Mines=100;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=2
Deep-Spacer=Alskant,5721889,8,3,13,ShipEquipment=Shields=350;Armor=250;Cargo Holds=300;Combat Drones=20;Scout Drones=0;Mines=25;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Demonica=Neutral,0,10,6,22,ShipEquipment=Shields=6666;Armor=6666;Cargo Holds=666;Combat Drones=1000;Scout Drones=0;Mines=1000;Scanner=1;Cloaking Device=1;Illusion Generator=1;Jump Drive=1;Drone Scrambler=1,Restrictions=2
Destroyer=Human,13719505,7,6,22,ShipEquipment=Shields=750;Armor=750;Cargo Holds=90;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Devastator=Creonti,11559082,6,8,26,ShipEquipment=Shields=300;Armor=1800;Cargo Holds=45;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Drudge=Salvene,875683,6,2,9,ShipEquipment=Shields=400;Armor=525;Cargo Holds=250;Combat Drones=0;Scout Drones=0;Mines=10;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Eater of Souls=Salvene,13306175,7,6,22,ShipEquipment=Shields=1050;Armor=950;Cargo Holds=30;Combat Drones=0;Scout Drones=0;Mines=25;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Escape Pod=Neutral,0,7,0,0,ShipEquipment=Shields=50;Armor=50;Cargo Holds=5;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Expediter=Thevian,1272250,9,0,0,ShipEquipment=Shields=375;Armor=475;Cargo Holds=180;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Favoured Offspring=Ik'Thorne,2486141,8,1,5,ShipEquipment=Shields=575;Armor=100;Cargo Holds=200;Combat Drones=10;Scout Drones=0;Mines=25;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Federal Discovery=Neutral,3335689,11,3,13,ShipEquipment=Shields=500;Armor=400;Cargo Holds=60;Combat Drones=30;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=1
Federal Ultimatum=Neutral,38675738,8,7,24,ShipEquipment=Shields=700;Armor=600;Cargo Holds=120;Combat Drones=15;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=1
Federal Warrant=Neutral,12026598,9,5,19,ShipEquipment=Shields=600;Armor=500;Cargo Holds=90;Combat Drones=20;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=1
Freighter=Neutral,5791393,10,1,5,ShipEquipment=Shields=300;Armor=300;Cargo Holds=250;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Fury=Nijarin,14724001,8,7,24,ShipEquipment=Shields=875;Armor=700;Cargo Holds=90;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=1,Restrictions=0
Galactic Semi=Neutral,0,8,1,5,ShipEquipment=Shields=150;Armor=175;Cargo Holds=60;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Goliath=Creonti,3380866,10,4,16,ShipEquipment=Shields=100;Armor=900;Cargo Holds=30;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Inter-Stellar Trader=Neutral,5914159,7,2,9,ShipEquipment=Shields=375;Armor=250;Cargo Holds=300;Combat Drones=5;Scout Drones=0;Mines=25;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Juggernaut=Creonti,5104130,8,5,19,ShipEquipment=Shields=150;Armor=1150;Cargo Holds=75;Combat Drones=25;Scout Drones=0;Mines=25;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Leviathan=Creonti,1122251,7,2,9,ShipEquipment=Shields=50;Armor=750;Cargo Holds=240;Combat Drones=25;Scout Drones=0;Mines=100;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Light Carrier=Neutral,783035,9,1,5,ShipEquipment=Shields=375;Armor=50;Cargo Holds=75;Combat Drones=10;Scout Drones=0;Mines=25;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Light Courier Vessel=Neutral,2530676,10,2,9,ShipEquipment=Shields=250;Armor=300;Cargo Holds=120;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Light Cruiser=Neutral,939440,7,3,13,ShipEquipment=Shields=350;Armor=275;Cargo Holds=75;Combat Drones=0;Scout Drones=0;Mines=10;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Light Freighter=Human,0,8,1,5,ShipEquipment=Shields=150;Armor=175;Cargo Holds=100;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Medium Cargo Hulk=Creonti,0,8,1,5,ShipEquipment=Shields=150;Armor=225;Cargo Holds=85;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Medium Carrier=Neutral,1630523,8,1,5,ShipEquipment=Shields=450;Armor=100;Cargo Holds=100;Combat Drones=10;Scout Drones=0;Mines=50;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Medium Cruiser=Neutral,1461380,6,4,16,ShipEquipment=Shields=400;Armor=300;Cargo Holds=115;Combat Drones=0;Scout Drones=0;Mines=20;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Merchant Vessel=Neutral,825408,9,2,9,ShipEquipment=Shields=250;Armor=325;Cargo Holds=170;Combat Drones=5;Scout Drones=0;Mines=5;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Mother Ship=Ik'Thorne,10432759,6,1,5,ShipEquipment=Shields=1000;Armor=50;Cargo Holds=120;Combat Drones=0;Scout Drones=0;Mines=50;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Negotiator=WQ Human,155234,11,1,5,ShipEquipment=Shields=200;Armor=150;Cargo Holds=40;Combat Drones=10;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Newbie Merchant Vessel=Neutral,0,9,2,9,ShipEquipment=Shields=500;Armor=500;Cargo Holds=170;Combat Drones=5;Scout Drones=0;Mines=5;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Planetary Freighter=Neutral,6115028,5,1,5,ShipEquipment=Shields=450;Armor=900;Cargo Holds=450;Combat Drones=5;Scout Drones=0;Mines=15;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Planetary Super Freighter=Neutral,6235792,4,1,5,ShipEquipment=Shields=650;Armor=1300;Cargo Holds=500;Combat Drones=5;Scout Drones=0;Mines=50;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Planetary Trader=Neutral,5983335,8,2,9,ShipEquipment=Shields=355;Armor=375;Cargo Holds=300;Combat Drones=5;Scout Drones=0;Mines=15;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Predator=Salvene,2823300,8,4,16,ShipEquipment=Shields=525;Armor=475;Cargo Holds=30;Combat Drones=10;Scout Drones=0;Mines=10;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Proto Carrier=Ik'Thorne,553810,9,2,9,ShipEquipment=Shields=400;Armor=125;Cargo Holds=120;Combat Drones=10;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Ravager=Salvene,6707691,8,5,19,ShipEquipment=Shields=650;Armor=675;Cargo Holds=30;Combat Drones=25;Scout Drones=0;Mines=50;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Rebellious Child=Ik'Thorne,273707,10,1,5,ShipEquipment=Shields=350;Armor=75;Cargo Holds=30;Combat Drones=50;Scout Drones=0;Mines=10;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Redeemer=Nijarin,0,9,1,5,ShipEquipment=Shields=100;Armor=100;Cargo Holds=75;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Renaissance=Human,606664,8,2,9,ShipEquipment=Shields=300;Armor=250;Cargo Holds=90;Combat Drones=10;Scout Drones=0;Mines=5;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Resistance=WQ Human,1156265,8,2,9,ShipEquipment=Shields=300;Armor=250;Cargo Holds=90;Combat Drones=10;Scout Drones=0;Mines=10;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Retaliation=Nijarin,435900,9,2,9,ShipEquipment=Shields=150;Armor=200;Cargo Holds=80;Combat Drones=10;Scout Drones=0;Mines=5;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=1,Restrictions=0
Retribution=Nijarin,3535800,9,4,16,ShipEquipment=Shields=300;Armor=300;Cargo Holds=70;Combat Drones=25;Scout Drones=0;Mines=10;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=1,Restrictions=0
Rogue=WQ Human,2074860,10,2,9,ShipEquipment=Shields=425;Armor=550;Cargo Holds=120;Combat Drones=50;Scout Drones=0;Mines=50;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Slayer=Neutral,0,10,1,5,ShipEquipment=Shields=1000;Armor=1000;Cargo Holds=60;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=1
Slip Freighter=WQ Human,0,9,1,5,ShipEquipment=Shields=150;Armor=150;Cargo Holds=90;Combat Drones=5;Scout Drones=0;Mines=10;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Small Escort=Neutral,520821,10,2,9,ShipEquipment=Shields=300;Armor=250;Cargo Holds=110;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Small-Timer=Alskant,0,9,1,5,ShipEquipment=Shields=150;Armor=150;Cargo Holds=100;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Spooky Midnight Special=Neutral,0,10,10,30,ShipEquipment=Shields=50000;Armor=21000;Cargo Holds=1000;Combat Drones=1000;Scout Drones=0;Mines=1000;Scanner=1;Cloaking Device=1;Illusion Generator=1;Jump Drive=1;Drone Scrambler=0,Restrictions=0
Star Ranger=Thevian,130923,12,1,5,ShipEquipment=Shields=225;Armor=200;Cargo Holds=0;Combat Drones=10;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Stellar Freighter=Neutral,7008455,9,1,5,ShipEquipment=Shields=250;Armor=400;Cargo Holds=225;Combat Drones=10;Scout Drones=0;Mines=15;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Swift Venture=Thevian,0,9,1,5,ShipEquipment=Shields=150;Armor=150;Cargo Holds=80;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Thief=Neutral,10802157,12,3,13,ShipEquipment=Shields=250;Armor=300;Cargo Holds=160;Combat Drones=0;Scout Drones=0;Mines=5;Scanner=1;Cloaking Device=1;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=2
Tiny Delight=Ik'Thorne,0,8,1,5,ShipEquipment=Shields=150;Armor=175;Cargo Holds=100;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=0;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Trade-Master=Alskant,12095764,9,2,9,ShipEquipment=Shields=675;Armor=525;Cargo Holds=200;Combat Drones=25;Scout Drones=0;Mines=100;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=1,Restrictions=0
Trip-Maker=Alskant,1354955,12,1,5,ShipEquipment=Shields=200;Armor=150;Cargo Holds=235;Combat Drones=0;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Unarmed Scout=Neutral,65251,12,0,0,ShipEquipment=Shields=300;Armor=175;Cargo Holds=30;Combat Drones=75;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=0,Restrictions=0
Vengeance=Nijarin,1137543,8,2,9,ShipEquipment=Shields=300;Armor=300;Cargo Holds=170;Combat Drones=5;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=1,Restrictions=0
Vindicator=Nijarin,7600000,8,6,22,ShipEquipment=Shields=425;Armor=400;Cargo Holds=50;Combat Drones=50;Scout Drones=0;Mines=75;Scanner=1;Cloaking Device=0;Illusion Generator=0;Jump Drive=0;Drone Scrambler=1,Restrictions=0
Watchful Eye=Salvene,135366,10,1,5,ShipEquipment=Shields=75;Armor=125;Cargo Holds=40;Combat Drones=100;Scout Drones=0;Mines=0;Scanner=1;Cloaking Device=0;Illusion Generator=1;Jump Drive=0;Drone Scrambler=0,Restrictions=0
```

**Comment by hemberger** [comment]
This will also need a numeric version in the filename before it is merged. Something like `V1_6_64_01__ship_starter_changes.sql`.

**Comment by hemberger** [comment]
One thing I noticed right away is that this makes the starter racial ships better traders than many of the cheap (less than 1 million credits) racial traders. Keep in mind also that only veterans will ever pilot these ships because newbies start with a Newbie Merchant Vessel, which is already a very good trader.

**Comment by stupidnewbie** [comment]
There are several trade ships which are incredibly cost ineffective.  The most efficient upgrade path for most races is Merchant Vessel straight to a 6 million credit end game trader.  I am going to submit another PR to that end that I think will make this make more sense.

Maybe I'm wrong about smoothing over the learning curve.  But I would still argue for these improvements on the grounds of softening the death penalty.  Anyone in these ships is paying an additional tax for being podded when they couldn't afford it.  They have to bootstrap cash 60 holds per trade in a ship vulnerable to being one shot.  I do not believe that is a fun game mechanic.

**Comment by hemberger** [comment]
I'm assuming this is made obsolete by #786? Should we close this one?

**Comment by stupidnewbie** [comment]
I had not included these changes in #786 but I could see the reasonableness of merging the two.

**Pull request closed without merging**
